version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  static:
    container_name: apache-static
    build:
      context: ../apache-php-image
    labels:
      - "traefik.http.routers.static.rule=Host(`localhost`)"
    restart: always
  dynamic:
    container_name: express-dynamic
    build:
      context: ../express-image
    labels:
      - "traefik.http.routers.dynamic.rule=Host(`localhost`) && PathPrefix(`/api/animals`)"
      - "traefik.http.routers.dynamic.middlewares=dynamic"
      - "traefik.http.services.dynamic.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.dynamic.stripprefix.prefixes=/api/animals"
    restart: always
