version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  static1:
    container_name: apache-static1
    build:
      context: ../apache-php-image
    labels:
      - "traefik.http.routers.static1.rule=Host(`localhost`)"
      - "traefik.http.services.static1.loadBalancer.sticky=true"
      - "traefik.http.services.static1.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.static1.loadBalancer.sticky.cookie.name=static1"
    restart: always
  static2:
    container_name: apache-static2
    build:
      context: ../apache-php-image
    labels:
      - "traefik.http.routers.static2.rule=Host(`localhost`)"
      - "traefik.http.services.static2.loadBalancer.sticky=true"
      - "traefik.http.services.static2.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.static2.loadBalancer.sticky.cookie.name=static2"
    restart: always
  dynamic:
    container_name: express-dynamic
    build:
      context: ../express-image
    labels:
      - "traefik.http.routers.dynamic.rule=Host(`localhost`) && PathPrefix(`/api/animals`)"
      - "traefik.http.routers.dynamic.middlewares=dynamic"
      - "traefik.http.services.dynamic.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.dynamic.stripprefix.prefixes=/api/animals"
    restart: always
  management:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
